services:
  learning_base:
    image: ghoshayan/learningbase_bitcoin_forecast:latest
    container_name: learningbase_bitcoin_forecast
    volumes:
      - ai_system:/tmp

volumes:
  ai_system:
    external: true